<a href="https://colab.research.google.com/github/jay-kanakia/GenAI/blob/main/1_Tensors_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
pip install torch

In [5]:
import torch

In [7]:
torch.cuda.is_available()

False

In [10]:
# using empty
a=torch.empty(2,3)
a

tensor([[2.1996e-02, 0.0000e+00, 3.2006e-28],
        [4.4920e-41, 8.9683e-44, 0.0000e+00]])

In [11]:
# check type
type(a)

torch.Tensor

In [12]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [13]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [14]:
# using rand
torch.rand(2,3)

tensor([[0.2540, 0.4148, 0.2742],
        [0.4139, 0.8084, 0.8884]])

In [16]:
# use of seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [19]:
# Key takeaway
# Input container type (list vs tuple) does not matter
# Tensor values, shape, and dtype are identical

# using tensor
torch.tensor(([1,2,3],[4,5,6]))
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [29]:
# other ways

# arange
torch.arange(1,10,2)

# using linspace
torch.linspace(1,10,5)

# using eye
torch.eye(5)

# using full
torch.full((2,2),6)

tensor([[6, 6],
        [6, 6]])

# Tensor Shapes

In [30]:
x=torch.tensor(([1,2,3],[4,5,6]))

In [31]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [32]:
x.shape

torch.Size([2, 3])

In [33]:
torch.empty_like(x)

tensor([[ 325422886882122853,                 171, 2187061136571243866],
        [3991349641173279844, 2772282616618165604, 7306086872103139369]])

In [34]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [35]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [38]:
torch.rand_like(x,dtype=torch.float64)

tensor([[0.1015, 0.6642, 0.9736],
        [0.6941, 0.3464, 0.9751]], dtype=torch.float64)

In [39]:
x.dtype

torch.int64

In [41]:
y=torch.tensor([1.0,2.0,3.0])
y

tensor([1., 2., 3.])

In [43]:
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [45]:
torch.tensor([1,2,3],dtype=torch.float32)

tensor([1., 2., 3.])

In [46]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [47]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

#Mathematical Operation

## Scalar Operation

In [51]:
x=torch.rand(2,3)
x

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])

In [58]:
# addition
x + 2
# substraction
x - 2
# # multiplication
x * 3
# # division
x / 3
# # int division
(x*100)//3
# # mod
((x*100)//3)%2
# # power
x**2

tensor([[0.0501, 0.0914, 0.0318],
        [0.6787, 0.3089, 0.9546]])

## Element wise operation

In [59]:
a=torch.rand(2,3)
a

tensor([[0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003]])

In [60]:
b=torch.rand(2,3)
b

tensor([[0.5277, 0.2472, 0.7909],
        [0.4235, 0.0169, 0.2209]])

In [66]:
# add
a+b
# sub
a-b
# # multiply
a*b
# # division
a/b
# # power
a**b
# # mod
a%b

tensor([[0.4440, 0.2063, 0.7445],
        [0.0657, 0.0060, 0.0377]])

In [71]:
c=torch.tensor([1,-2,3,-4])
d=torch.rand(2,3)+1
d

tensor([[1.6476, 1.3430, 1.3182],
        [1.5261, 1.0447, 1.5123]])

In [76]:
# abs
torch.abs(c)

# negative
torch.neg(c)

# round
torch.round(d)

# ceil
torch.ceil(d)

# floor
torch.floor(d)

# clamp
torch.clamp(d,min=1.5,max=1.6)

tensor([[1.6000, 1.5000, 1.5000],
        [1.5261, 1.5000, 1.5123]])

## Reduction operation

In [80]:
e=torch.randint(size=(2,3),low=2,high=8,dtype=torch.float16)
e

tensor([[7., 7., 2.],
        [5., 2., 7.]], dtype=torch.float16)

In [95]:
# sum
torch.sum(e)

# sum along columns
torch.sum(e,dim=0)

# sum along rows
torch.sum(e,dim=1)

# mean
torch.mean(e)

# mean along col
torch.mean(e,dim=0)

# median
torch.median(e)

# max and min
torch.max(e,dim=0)
torch.min(e,dim=1)

# product
torch.prod(e,dim=1)

# standard deviation
torch.std(e,dim=0)

# variance
torch.var(e,dim=1)

# argmax
torch.argmax(e,dim=0)

# argmin
torch.argmin(e,dim=1)

tensor([2, 1])

## Matrix operations

In [96]:
a=torch.randint(size=(2,3),low=2,high=14)
b=torch.randint(size=(3,2),low=4,high=12)

In [97]:
# matrix multiplcation
torch.matmul(a,b)

tensor([[203, 250],
        [249, 295]])

In [100]:
a=torch.tensor([1,2,3])
b=torch.tensor([4,5,6])

torch.dot(a,b)

tensor(32)

In [105]:
a=torch.randint(size=(2,3),low=2,high=14)
a

tensor([[6, 8, 9],
        [4, 5, 6]])

In [107]:
torch.transpose(a,0,1)

tensor([[6, 4],
        [8, 5],
        [9, 6]])

In [108]:
torch.transpose(a,1,0)

tensor([[6, 4],
        [8, 5],
        [9, 6]])

In [112]:
a=torch.randint(size=(3,3),low=2,high=14,dtype=torch.float64)
torch.det(a)

tensor(-472.0000, dtype=torch.float64)

In [113]:
torch.inverse(a)

tensor([[-0.0508,  0.0678,  0.0297],
        [ 0.0847,  0.2203, -0.2161],
        [ 0.0339, -0.2119,  0.1886]], dtype=torch.float64)

## Comparison operations

In [120]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[1, 5, 0],
        [2, 3, 7]])
tensor([[0, 2, 5],
        [2, 8, 0]])


In [124]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to
i>=j
# less than equal to
i<=j

tensor([[False, False,  True],
        [ True,  True, False]])

## Special functions

In [132]:
a=torch.randint(size=(2,3),low=3,high=15,dtype=torch.float64)
a

tensor([[ 4.,  9., 14.],
        [ 7., 14.,  4.]], dtype=torch.float64)

In [136]:
#log
torch.log(a)

#exp
torch.exp(a)

#sqrt
torch.sqrt(a)

#sigmoid
torch.sigmoid(a)

#softmax
torch.softmax(a,dim=0)

#relu
torch.relu(a)


tensor([[ 4.,  9., 14.],
        [ 7., 14.,  4.]], dtype=torch.float64)

## Inplace Operations

In [141]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.3436, 0.2028, 0.9792],
        [0.4947, 0.3617, 0.9687]])
tensor([[0.0359, 0.3041, 0.9867],
        [0.1290, 0.6887, 0.1637]])


In [142]:
m+n

tensor([[0.3795, 0.5069, 1.9659],
        [0.6237, 1.0504, 1.1323]])

In [143]:
m

tensor([[0.3436, 0.2028, 0.9792],
        [0.4947, 0.3617, 0.9687]])

In [144]:
n

tensor([[0.0359, 0.3041, 0.9867],
        [0.1290, 0.6887, 0.1637]])

In [145]:
m.add_(n)

tensor([[0.3795, 0.5069, 1.9659],
        [0.6237, 1.0504, 1.1323]])

In [146]:
m

tensor([[0.3795, 0.5069, 1.9659],
        [0.6237, 1.0504, 1.1323]])

In [147]:
n

tensor([[0.0359, 0.3041, 0.9867],
        [0.1290, 0.6887, 0.1637]])

In [151]:
x=torch.rand(2,3)-0.5
x

tensor([[-0.2560,  0.3994, -0.3959],
        [ 0.4193,  0.1201, -0.1342]])

In [152]:
torch.relu(x)

tensor([[0.0000, 0.3994, 0.0000],
        [0.4193, 0.1201, 0.0000]])

In [153]:
x

tensor([[-0.2560,  0.3994, -0.3959],
        [ 0.4193,  0.1201, -0.1342]])

In [155]:
torch.relu_(x)

tensor([[0.0000, 0.3994, 0.0000],
        [0.4193, 0.1201, 0.0000]])

In [156]:
x

tensor([[0.0000, 0.3994, 0.0000],
        [0.4193, 0.1201, 0.0000]])

## Copying a Tensor

In [167]:
a = torch.rand(2,3)
a

tensor([[0.9840, 0.5836, 0.6737],
        [0.4738, 0.9336, 0.2557]])

In [168]:
b=a
b

tensor([[0.9840, 0.5836, 0.6737],
        [0.4738, 0.9336, 0.2557]])

In [169]:
a[0][0]=0
a

tensor([[0.0000, 0.5836, 0.6737],
        [0.4738, 0.9336, 0.2557]])

In [170]:
b

tensor([[0.0000, 0.5836, 0.6737],
        [0.4738, 0.9336, 0.2557]])

In [171]:
id(a),id(b)

(137678445451760, 137678445451760)

In [172]:
b=torch.clone(a)
a

tensor([[0.0000, 0.5836, 0.6737],
        [0.4738, 0.9336, 0.2557]])

In [173]:
b

tensor([[0.0000, 0.5836, 0.6737],
        [0.4738, 0.9336, 0.2557]])

In [174]:
a[0][0]=10
a

tensor([[10.0000,  0.5836,  0.6737],
        [ 0.4738,  0.9336,  0.2557]])

In [175]:
b

tensor([[0.0000, 0.5836, 0.6737],
        [0.4738, 0.9336, 0.2557]])

In [176]:
id(a),id(b)

(137678445451760, 137678447689264)