<a href="https://colab.research.google.com/github/jay-kanakia/GenAI/blob/main/2_Pytorch_Autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [9]:
x=torch.tensor(2.0,requires_grad=True)
y=x**2
z=torch.sin(y)

In [10]:
z.backward()

In [11]:
x.grad

tensor(-2.6146)

In [12]:
x

tensor(2., requires_grad=True)

In [13]:
y

tensor(4., grad_fn=<PowBackward0>)

In [14]:
z

tensor(-0.7568, grad_fn=<SinBackward0>)

In [8]:
x=torch.tensor(2.0,requires_grad=True)
y=x**2
y.backward()
x.grad

tensor(4.)

In [15]:
# clearing tensor

In [17]:
# option 1 - requires_grad_(False)
x=torch.tensor([1.0,2.0,3.0],requires_grad=True)
x

tensor([1., 2., 3.], requires_grad=True)

In [20]:
y=x**2
y

tensor([1., 4., 9.], grad_fn=<PowBackward0>)

In [27]:
#Gradients are defined for scalar-valued functions
z=torch.sin(y).mean()
z

tensor(0.1656, grad_fn=<MeanBackward0>)

In [24]:
z.backward()
x.grad

tensor([ 0.3602, -0.8715, -1.8223])

In [28]:
x.requires_grad_(False)
x

tensor([1., 2., 3.])

In [29]:
y

tensor([1., 4., 9.], grad_fn=<PowBackward0>)

In [30]:
z

tensor(0.1656, grad_fn=<MeanBackward0>)

In [31]:
z.backward()

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [32]:
# option 2 - detach()
x=torch.tensor([1.0,2.0,3.0],requires_grad=True)
y=x**2
z=torch.sin(y).mean()
z.backward()
x.grad

tensor([ 0.3602, -0.8715, -1.8223])

In [33]:
k=x.detach()

In [34]:
x.grad

tensor([ 0.3602, -0.8715, -1.8223])

In [36]:
y1=k**2
y1

tensor([1., 4., 9.])

In [37]:
y1.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [38]:
# option 3 - torch.no_grad()

x=torch.tensor([1.0,2.0,3.0],requires_grad=True)
y=x**2
z=torch.sin(y).mean()
z.backward()
x.grad

tensor([ 0.3602, -0.8715, -1.8223])

In [41]:
with torch.no_grad():
  y=x**2

y

tensor([1., 4., 9.])

In [40]:
x

tensor([1., 2., 3.], requires_grad=True)